apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: ingress
  metrics:
  - name: success-rate
    interval: 10s
    successCondition: len(result) == 0 || result[0] >= 0.50
    provider:
      prometheus:
        # address: http://prometheus-server.prometheus.svc.cluster.local:80
        address: https://aps-workspaces.us-east-2.amazonaws.com/workspaces/ws-5183df0b-8c0b-4842-8b4d-11374db447e3
        query: >+
          sum(
            rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}",status!~"[4-5].*"}[20s]))
            /
            sum(rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}"}[20s])
          )
